version: '3.9'
volumes:
    data-elasticsearch:
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        volumes: 
            - data-elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        container_name: elasticsearch_plataform

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://localhost:9200
        container_name: kibana_plataform
